---
name: module3_task1

'on':
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Clone the repository
        uses: actions/checkout@v3

      - name: Run setup environment
        run: |
          cd ./module3_task1
          ./setup.sh
          make build
