---
name: module3_task3

'on':
  push:
    branches:
      - main
    tags:
      - '*'
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Clone the repository
        uses: actions/checkout@v3

      - name: Run setup environment
        run: |
          cd ./module3_task3
          ./setup.sh
          make build
          make lint
          make unit-tests
          make integration-tests
          make validate
          make package
      - name: archive
        uses: actions/upload-artifact@v2
        with:
          name: awesome-website
          path: ./module3_task3/awesome-website.zip

  create-release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-22.04
    steps:
      - name: Clone the repository
        uses: actions/checkout@v3

      - name: install the Markdownlint
        run: npm install -g markdownlint-cli

      - name: Install Hugo
        run: |
            cd module3_task3
            ./setup.sh

      - name: create package
        run: |
            cd ./module3_task3
            make package

      - name: release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: ./module3_task3/awesome-website.zip
          body_path: ./module3_task3/DEPLOY.md
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
