name: module3_task4

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Clone the repository
        uses: actions/checkout@v3
      - name: Run the script
        run: cd module3_task4 && ./setup.sh
      - name: Makefile build
        run: cd module3_task4 && make build
      - name: Archive
        run: cd module3_task4 && make package
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: building package
          path: module3_task4/awesome-website.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: 1.0.0
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            module3_task4/awesome-website.zip
            module3_task4/DEPLOY.md
  buildonotherversion:
    runs-on: ubuntu-18.04
    if: github.event_name == 'push' && github.ref_type == 'tag'
    steps:
      - name: Clone the repository
        uses: actions/checkout@v3
      - name: Run the script
        run: cd module3_task4 && ./setup.sh
      - name: Makefile build
        run: cd module3_task4 && make build
      - name: Archive
        run: cd module3_task4 && make package
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: build package
          path: module3_task4/awesome-website.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: 1.0.0
          release_name: "1.0.0"
          files: |
            module3_task4/awesome-website.zip
            module3_task4/DEPLOY.md